### ISSUE TITLE
Clickable markers

### ISSUE THREAD

**Issue by saifanam** [mikefowler/smallworld.js#1]
Are there any plans to make the markers clickable? Like when it's clicked, it shows the lat-long pair and perhaps the reverse geocoded address within a speech bubble.

**Comment by kostasx** [comment]
@saifanam Check out my [fork](https://github.com/kostasx/smallworld.js) which introduces clickable markers that display both longitude/latitude and address (on the console). It currently only works with a single marker. It also need some minor fixes, since the event fires twice. I really didn't have the time to correctly implement this functionality, so any help would really be appreciated.

**Comment by mikefowler** [comment]
Hey @saifanam, @kostasx,

Thanks for checking the tool out and for the feedback!

At this point, there are no plans to support the suggested functionality. If anything, I would consider implementing hooks for certain events (like clicking a marker). Taking a certain course of action upon a click event (for example) would be too prescriptive for the intent of this project. As it is, I think even hooks for click (or other) events might be too prescriptive. I'll think it over.

**Comment by saifanam** [comment]
@mikefowler, How about the jQuery model? Perhaps we keep the core simple and allow to add plugins as needed? (like click events)

**Comment by saifanam** [comment]
@kostasx, @mikefowler, please take a look at this: https://github.com/saifanam/smallworld.js/compare/patch-1

**Comment by shshaw** [comment]
By adding interactivity to smallworld, it could become a very handy UI component. Currently, I'm stuck using large & complex SVG maps for "Locations" maps, but with some extensibility or hooks, smallworld would be a very useful and lightweight alternative.

**Comment by mikefowler** [comment]
Agreed, @shshaw. @saifanam, this seems like a good start. I'll look at it in more detail soon and provide some feedback/thoughts.

**Comment by mikefowler** [comment]
@shshaw, what kind of additional features are you mostly using with other libraries? Is it mostly basic things like click and hover? And what actions/events occur based on those clicks, hovers, etc?

**Comment by mikefowler** [comment]
@saifanam, @kostasx, @shshaw: Thoughts on an API that might look like this? `markerEvents` would be an optional attribute that, when defined, would create the appropriate DOM events based on the keys of the object (like “click” or “hover”). The callbacks would be run with the marker details (lat/lng, possibly size, color, etc).

``` javascript
$('.map').smallworld({
  center: [0, 0],
  markers: [
    [20, -100],
    [80, 50]
  ],
  markerEvents: {
    click: function (marker) {
      // ...
    },
    hover: function (marker) {
      // ...
    }
  }
});
```

**Comment by shshaw** [comment]
@mikefowler Last map I built was with D3.js and Topojson. You can see it here: http://scientificdrilling.com/

D3 gets the job done, but is insanely complex (500+ lines, not including D3, Topojson & map data to get the interactions shown on Scientific Drilling). Also, the SVG map data is huge, polluting the DOM with hundreds of elements. Certainly not the best way to render map data! Here's the main map Javascript if you're interested in how it all works within D3's API: https://gist.github.com/shshaw/9e49ea23d68eb761701b

I haven't worked much with canvas, so I don't know how easy it would be to do these sort of manipulations or what the possibility of animation is with Smallworld, but ideally a full featured map API would be able to dynamically:
- **Zoom** - Click plus or minus to zoom in / out, use mousewheel events to trigger zooms, or dynamically zoom in to a marker when clicked.
- **Center** - Move map center to an area, focus in on a marker when clicked.
- **Drag to Pan** - Allows user to explore the map.

In my mind, markers are each an object with several attributes and capabilities:
- **Fire click & hover events** - This is useful for showing more details for a location, probably outside of the map, but could be useful to have a popup like in Google Maps.
- **Add / remove markers.** - Focus on markers in specific regions, or add additional markers if the user selects a category...'
- **Highlight markers** - Give prominence to a marker or set of markers. Like on hover, or with a user filter on the page

The API might look something like this:

``` js
var myMap = $('.map').smallworld({
  center: [0, 0],
  zoom: 1,
  markers: [{
    name: "Houston", // Unique identifier to give greater functionality in the marker events (show name on hover, reveal marker details on click, etc)
    latlng: [29.79,-95.41], // Coordinates
    color: "#FF0000" // Color of dot, instead of an icon
  }],
  markerEvents: { // `click` and `hover` are the only events I use... Not sure what other events would be useful.
    hover: function (marker) {},
    click: function (marker) {
       myMap.center(marker.latlng);
       myMap.zoom(5);
       alert(marker.name);
    }
});

// You could also add markers later on and be able to reference them directly.
var dallasMarker = myMap.addMarker({
  name: "Dallas",
  latlng: [32.78,-96.80],
  icon: "/img/marker.png" // Image to be used instead of dot. Allows for Google Maps style markers
});

// Being able to attach events to individual markers for even more custom events would be nice
dallasMarker.on("click",function(){
  var marker = this;
  $("#"+marker.name+"-Details").fadeToggle(); // Show/hide this marker's details box on the page.
});
```

This is just based on my experience in building maps for client sites. An API designed to do these things would vastly simplify the map creation process!

**Comment by shshaw** [comment]
I realize the above features add a lot of complexity to what is intended to be a lightweight map builder. Adding hover/click events to markers is the most basic functionality that would add a lot of utility to smallworld, even without any of the other features.

However, smallworld could fill a huge niche in web development by adding in the other functionality to really make the map dynamic.

Perhaps the best approach would be to keep the core smallworld script lightweight, then be able to add in modules for animations, dynamic zooming / centering, finer marker control, etc. Then developers can just add the modules they need for the map they're building and keep scripts lightweight.
