### ISSUE TITLE
Mystery numbers in tile size segment

### ISSUE THREAD

**Issue by scottopell** [mikefowler/smallworld.js#5]
Was going through the code and trying to figure out how everything ties together, was wondering what the "magic" numbers for the tile dimensions signify.

https://github.com/mikefowler/smallworld.js/blob/master/src/smallworld.js#L203

``` javascript
      // Set the dimensions of the tile
      this.width = Math.ceil(256 * this.scale);
      this.height = Math.ceil(this.width / 1.041975309);
```

Could you explain a bit what these numbers signify?

Thanks for the great code!

**Comment by scottopell** [comment]
Also this one
https://github.com/mikefowler/smallworld.js/blob/master/src/smallworld.js#L310

``` javascript
  Smallworld.Projection = {

    RADIUS: 6378137,

    MAX: 85.0511287798,

    RADIANS: Math.PI / 180,
```

Is this `MAX` specific to the mercator projection?
Googling seems to suggest it's tied to the tile concept in some way?

**Comment by mikefowler** [comment]
Oooof. Guess I should have left a comment on the first bit. Let me think that one over.

The second set of magic numbers are specific to Mercator projections. `85.0511287798` is the maximum latitude covered by Mercator projections, and `6378137` is (maybe obvious) the radius of the Earth (in meters).
